### ISSUE TITLE
Error on Mojave after running (New Wemessage User)

### ISSUE THREAD

**Issue by gotmax23** [RomanScott/weMessage#10]
Hi,

I am running Wemessage on a virtual Mojave installation. I have iMessage set up and working. The WeServer starts, recognizes messages, and everything, but after starting this error comes up and the Android app says "Couldn't establish connection to server" after I typed in the IP address, email, and password. FYI, I did allow terminal Accessibility and Full Disk Access.

maxwells-Mac:~ maxwellgottlieb$ /Users/maxwellgottlieb/Downloads/weServer/run.command ; exit;
 
[INFO] [weServer] Starting weServer on port 22222
[INFO] [weServer Database Service] Database Service has started
[INFO] [Messages Database Service] Connecting to Messages Database
[INFO] [weServer Event Manager] Event manager has started
[INFO] [weServer Device Service] Device Service has started
[INFO] [weServer Command Service] Commands Service has started
 
weServer Started!
Version: 1.2
 
[!!! ERROR !!!] An error occurred while checking for updates
 
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at com.google.gson.Gson.fromJson(Gson.java:774)
	at scott.wemessage.server.b.a.c.run(SourceFile:30)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 5 more
 
The database commands like lastmessage work and it seems to be communicating with iMessage, but it is not connecting to my Galaxy S9.

Thanks for your hard work.

**Comment by gotmax23** [comment]
Hope that made sense. :)

**Comment by scottmusson** [comment]
Same issue

**Comment by seawatts** [comment]
I'm also getting the same thing

**Comment by adamwgray** [comment]
You need to enable full disk access for that to resolve itself. It is the same basic steps as accessibility.

**Comment by gotmax23** [comment]
I did that. It still doesn't work.

**Comment by whikloj** [comment]
My first time trying this software and I'm getting this same error message. I am running OSX Big Sur (11.4). I use jenv to allow multiple java versions but have altered the `run.command` file to have the `java` replaced with the full path to my 11.0.3 installation. 

java has full disk and accessibility access.

I deleted the extracted directory and re-extracted it. I changed the permissions on `run.command` to allow execute and re-made the change to point to the java 11 installation. I double click `run.command`

```
> /Applications/weServer/run.command ; exit;
 
The email and password provided in config.json are invalid!
 
Please enter a new email and password for devices to connect with!
Your email must be the same as the one you are using iMessage with.
 
XXXX [obufscated] XXXX 
 
Please enter a new password for devices to connect with!
 
XXXX [obufscated] XXXX 
[INFO] [weServer] Starting weServer on port 22222
[INFO] [weServer Database Service] Database Service has started
[INFO] [Messages Database Service] Connecting to Messages Database
[INFO] [weServer Event Manager] Event manager has started
[INFO] [weServer Command Service] Commands Service has started
[INFO] [weServer Device Service] Device Service has started
 
weServer Started!
Version: 1.2
 
[!!! ERROR !!!] An error occurred while checking for updates
 
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at com.google.gson.Gson.fromJson(Gson.java:774)
	at scott.wemessage.server.b.a.c.run(SourceFile:30)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 5 more
```

**Comment by hunterwilhelm** [comment]
I just had the same error and resolved it by changing the JAVA_HOME path on my computer to Java 11. Java 19 did not work
