### ISSUE TITLE
sentry-cmd.txt - help/explanation?

### ISSUE THREAD

**Issue by marchharesoftware** [RomanScott/weMessage#19]
Can you explain sentry-cmd.txt a little?

When I build weServer I don't get any mapping generated, so the "upload-proguard " generates an error " 'server/lib/proguard/out.map' does not exist. " and then weServer also gives an error.

Any help appreciated...

When I try and run sentry-cli I get:

`sentry-cli --auth-token blahblahblah upload-proguard --org march-hare-software --project wemessage --write-properties sentry-meta.properties server/lib/proguard/out.map
sentry-cli --auth-token 5cfa334af20b49b89fae48adb7ba409c098580460e594feeb8f910c7e4a61bde upload-proguard --org march-hare-software --project wemessage --write-properties sentry-meta.properties server/lib/proguard/out.map
warning: proguard mapping 'server/lib/proguard/out.map' does not exist. This might be because the build process did not generate one (for instance because -dontobfuscate is used)
> compressing mappings
> uploading mappings
> Uploaded a total of 0 new mapping files
`

When I run weServer I get:
` 
java.lang.NullPointerException: inStream parameter is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at java.base/java.util.Properties.load(Properties.java:403)
	at scott.wemessage.server.utils.SentryEventHelper.getProGuardUuids(SentryEventHelper.java:60)
	at scott.wemessage.server.utils.SentryEventHelper.helpBuildingEvent(SentryEventHelper.java:37)
	at io.sentry.SentryClient.runBuilderHelpers(SentryClient.java:116)
	at io.sentry.SentryClient.sendEvent(SentryClient.java:173)
	at io.sentry.Sentry.capture(Sentry.java:177)
	at scott.wemessage.server.ServerLogger.logToSentry(ServerLogger.java:208)
	at scott.wemessage.server.ServerLogger.logToSentry(ServerLogger.java:170)
	at scott.wemessage.server.ServerLogger.error(ServerLogger.java:120)
	at scott.wemessage.server.ServerLogger.error(ServerLogger.java:100)
	at scott.wemessage.server.ServerLogger.error(ServerLogger.java:96)
	at scott.wemessage.server.connection.http.VersionChecker.run(VersionChecker.java:59)`

**Comment by marchharesoftware** [comment]
OK, so your notes contain this:

> Set the task for :server:build and under arguments use the following parameter: jar dependencyJar proguard. This will build the dependency.jar and weServer.jar

I completely don't understand this, and obviously set it up wrong (see screenshot).  

<img width="1074" alt="how to - server - run - task" src="https://user-images.githubusercontent.com/38123089/53133174-45a8d500-35c6-11e9-972e-5c12d528e871.png">


Also I wasn't using 'Run' to build, I was using Build->Make Project to build, so that wasn't being triggered anyway.

Easiest solution I found was to add this to the end of build.gradle (module: weServer):

`assemble.dependsOn dependencyJar, proguard`

Now using Build->Make Project causes the out.map to be created.

Some feedback on how the "Set the task for :server:build" is supposed to work/look would be great, so I'll leave the issue as open.
