### ISSUE TITLE
Crashing on initial boot (new user)

### ISSUE THREAD

**Issue by Damatios** [RomanScott/weMessage#23]
Hey there! So I am running OS Mojave 10.14.4 and have JDK 12 installed. I followed all the directions to set up the weServer, but keep getting this error:

```
[!!! ERROR !!!] [weServer Database Service] An error occurred while connecting to the Messages Chat database. Shutting down!
 
java.sql.SQLException: The database has been closed
	at org.sqlite.core.NativeDB.throwex(NativeDB.java:471)
	at org.sqlite.core.NativeDB.errmsg_utf8(Native Method)
	at org.sqlite.core.NativeDB.errmsg(NativeDB.java:137)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB._open_utf8(Native Method)
	at org.sqlite.core.NativeDB._open(NativeDB.java:71)
	at org.sqlite.core.DB.open(DB.java:174)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:25)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at scott.wemessage.server.c.a.<init>(SourceFile:120)
	at scott.wemessage.server.a.<init>(SourceFile:79)
	at scott.wemessage.server.ServerLauncher.main(SourceFile:8)
 
The email and password provided in config.json are invalid!
 
Please enter a new email and password for devices to connect with!
Your email must be the same as the one you are using iMessage with.
 
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```
Any suggestions? This happens whether the email is "email@icloud.com" (the default, I assume) or my actual iMessage account. I'll keep seeing if I can get it to reset/ run, but it doesn't look promising as I cannot enter any of the commands.

**Comment by ngkline** [comment]
I am having a similar issue, tried to delete and re-download. Did not work. Did OP find a fix?

**Comment by evanoe7** [comment]
I'm having this issue as well. Any resolution yet?

**Comment by aphexcx** [comment]
Same here. Can't proceed past this point to any of the setup. Please respond!

**Comment by Chandlerblaid** [comment]
I also have this issue

**Comment by alex4108** [comment]
I gave Java and Terminal Full Disk Access & Accessibility permissions and got past this crash.

**Comment by tcco** [comment]
This [method](https://github.com/RomanScott/weMessage/blob/master/server/src/main/java/scott/wemessage/server/security/Authenticator.java#L56) in the Authenticator class is where it is breaking for me. First off, you have to change the email, password, and secret from the default values. After doing so you'll get to the error thrown on line 58.

There I generated a valid 10 rounded salt but also realized `test` actually has to be your password in config.json. The bug, however, is that hashPassword from bcrypt expects bytes rather than strings.

**Comment by Elsa224** [comment]
> I gave Java and Terminal Full Disk Access & Accessibility permissions and got past this crash.

It worked for me!

**Comment by cssjr** [comment]
> I gave Java and Terminal Full Disk Access & Accessibility permissions and got past this crash.

How do you do this?  Sorry mac n00b

**Comment by alex4108** [comment]
System Preferences... Privacy & Security button... Privacy tab I think


Alex Schittko
Information Technology Manager
*P*  817-756-4852
*E*  ***@***.***| *Schedule a Meeting*
<https://calendly.com/aschittko/>
https://www.granburysolutions.com
  <https://facebook.com/GranburySolutions>
<https://twitter.com/GRSTechTweets>
<https://www.linkedin.com/company/1085773>

*[image: Share Your Experience with Granbury Solutions on Google]
<https://g.page/GranburySolutions/review?rc>*
[image: -]

IMPORTANT: This message (including any attachments) may contain
confidential information and is intended solely for the recipient(s). Any
disclosure, distribution, or reproduction of this message or any
attachments without written consent is strictly prohibited.
