### ISSUE TITLE
Cannot get weMessage to run

### ISSUE THREAD

**Issue by SamJeigh** [RomanScott/weMessage#30]
Hello! I am trying to download and run weMessage, I am running macOS Catalina version 10.15.2. I have added terminal to accessibility and I have Java installed but keep getting this message:

[!!! ERROR !!!] [weServer Database Service] An error occurred while connecting to the Messages Chat database. Shutting down!
 
java.sql.SQLException: The database has been closed
	at org.sqlite.core.NativeDB.throwex(NativeDB.java:471)
	at org.sqlite.core.NativeDB.errmsg_utf8(Native Method)
	at org.sqlite.core.NativeDB.errmsg(NativeDB.java:137)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB._open_utf8(Native Method)
	at org.sqlite.core.NativeDB._open(NativeDB.java:71)
	at org.sqlite.core.DB.open(DB.java:174)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:25)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at scott.wemessage.server.c.a.<init>(SourceFile:120)
	at scott.wemessage.server.a.<init>(SourceFile:79)
	at scott.wemessage.server.ServerLauncher.main(SourceFile:8)
 
 

[Process completed]

Any help with the above would be more than appreciated!

**Comment by cedarlug** [comment]
https://github.com/RomanScott/weMessage/issues/27#issuecomment-572307135
