### ISSUE TITLE
MacOs Bigsur Terminal Issue.

### ISSUE THREAD

**Issue by Kief5555** [RomanScott/weMessage#38]
There is a terminal issue, when I run the .command file (with all permission needed) it gives me this error:
Last login: Fri Dec 11 19:14:39 on ttys004
/Users/kieferlin/Downloads/weServer/run.command ; exit;                         
kieferlin@Kiefers-MBP ~ % /Users/kieferlin/Downloads/weServer/run.command ; exit;
<JAVA_HOME>/lib/ext exists, extensions mechanism no longer supported; Use -classpath instead.
.Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

(I will send a screenshot too)

<img width="486" alt="Screen Shot 2020-12-11 at 7 18 06 PM" src="https://user-images.githubusercontent.com/67562560/101971343-9b100500-3be5-11eb-8605-19ad4f44c341.png">

**Comment by Kief5555** [comment]
Btw I am running macOs BigSur 1.0.1

**Comment by slugger414** [comment]
I am installing weserver on Big Sur and having a similar issue. Has anyone gotten it running on Big Sur?

Air:weServer krt263$ ./run.command
 
[!!! ERROR !!!] [weServer Database Service] An error occurred while connecting to the Messages Chat database. Shutting down!
 
java.sql.SQLException: The database has been closed
	at org.sqlite.core.NativeDB.throwex(NativeDB.java:471)
	at org.sqlite.core.NativeDB.errmsg_utf8(Native Method)
	at org.sqlite.core.NativeDB.errmsg(NativeDB.java:137)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB._open_utf8(Native Method)
	at org.sqlite.core.NativeDB._open(NativeDB.java:71)
	at org.sqlite.core.DB.open(DB.java:174)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:25)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at scott.wemessage.server.c.a.<init>(SourceFile:120)
	at scott.wemessage.server.a.<init>(SourceFile:79)
	at scott.wemessage.server.ServerLauncher.main(SourceFile:8)
 
 [01-22-2021 09:59:16] The email and password provided in config.json are invalid!
 
[01-22-2021 09:59:16] Please enter a new email and password for devices to connect with!
[01-22-2021 09:59:16] Your email must be the same as the one you are using iMessage with.


I never get prompted for email and password.

Scott

**Comment by nerdXNature** [comment]
Yeah, I'm getting a similar issue on `macOS Catalina 10.15.7`. I was able to get my credentials entered by writing an apple script that quickly entered them before the process ended, however I'm still stuck with this issue.

I also tried connecting to the server in the small window of time between when it says `weServer Started!` and `[Process completed]`. Still no luck.

Here's what it returned:
```
[!!! ERROR !!!] [weServer Database Service] An error occurred while connecting to the Messages Chat database. Shutting down!
 
java.sql.SQLException: The database has been closed
	at org.sqlite.core.NativeDB.throwex(NativeDB.java:471)
	at org.sqlite.core.NativeDB.errmsg_utf8(Native Method)
	at org.sqlite.core.NativeDB.errmsg(NativeDB.java:137)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB._open_utf8(Native Method)
	at org.sqlite.core.NativeDB._open(NativeDB.java:71)
	at org.sqlite.core.DB.open(DB.java:174)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:25)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at scott.wemessage.server.c.a.<init>(SourceFile:120)
	at scott.wemessage.server.a.<init>(SourceFile:79)
	at scott.wemessage.server.ServerLauncher.main(SourceFile:8)
 
 
[INFO] [weServer] Starting weServer on port 22222
[INFO] [Messages Database Service] Connecting to Messages Database
[INFO] [weServer Event Manager] Event manager has started
[INFO] [weServer Database Service] Database Service has started
[INFO] [weServer Device Service] Device Service has started
[INFO] [weServer Command Service] Commands Service has started
 
weServer Started!
Version: 1.2
 

[Process completed]
```

**Comment by SeanBottomley** [comment]
> I am installing weserver on Big Sur and having a similar issue. Has anyone gotten it running on Big Sur?
> 
> Air:weServer krt263$ ./run.command
> 
> [!!! ERROR !!!] [weServer Database Service] An error occurred while connecting to the Messages Chat database. Shutting down!
> 
> java.sql.SQLException: The database has been closed
> at org.sqlite.core.NativeDB.throwex(NativeDB.java:471)
> at org.sqlite.core.NativeDB.errmsg_utf8(Native Method)
> at org.sqlite.core.NativeDB.errmsg(NativeDB.java:137)
> at org.sqlite.core.DB.newSQLException(DB.java:921)
> at org.sqlite.core.DB.throwex(DB.java:886)
> at org.sqlite.core.NativeDB._open_utf8(Native Method)
> at org.sqlite.core.NativeDB._open(NativeDB.java:71)
> at org.sqlite.core.DB.open(DB.java:174)
> at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
> at org.sqlite.core.CoreConnection.(CoreConnection.java:76)
> at org.sqlite.jdbc3.JDBC3Connection.(JDBC3Connection.java:25)
> at org.sqlite.jdbc4.JDBC4Connection.(JDBC4Connection.java:24)
> at org.sqlite.SQLiteConnection.(SQLiteConnection.java:45)
> at org.sqlite.JDBC.createConnection(JDBC.java:114)
> at org.sqlite.JDBC.connect(JDBC.java:88)
> at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
> at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
> at scott.wemessage.server.c.a.(SourceFile:120)
> at scott.wemessage.server.a.(SourceFile:79)
> at scott.wemessage.server.ServerLauncher.main(SourceFile:8)
> 
> [01-22-2021 09:59:16] The email and password provided in config.json are invalid!
> 
> [01-22-2021 09:59:16] Please enter a new email and password for devices to connect with!
> [01-22-2021 09:59:16] Your email must be the same as the one you are using iMessage with.
> 
> I never get prompted for email and password.
> 
> Scott

Did you edit the json file?

**Comment by slugger414** [comment]
No. I just downloaded again and ran run.command, getting the same message.

thanks -
