### ISSUE TITLE
Database has been closed error

### ISSUE THREAD

**Issue by vatche-k3** [RomanScott/weMessage#39]
[!!! ERROR !!!] [weServer Database Service] An error occurred while connecting to the Messages Chat database. Shutting down!
 
java.sql.SQLException: The database has been closed
	at org.sqlite.core.NativeDB.throwex(NativeDB.java:471)
	at org.sqlite.core.NativeDB.errmsg_utf8(Native Method)
	at org.sqlite.core.NativeDB.errmsg(NativeDB.java:137)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB._open_utf8(Native Method)
	at org.sqlite.core.NativeDB._open(NativeDB.java:71)
	at org.sqlite.core.DB.open(DB.java:174)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:25)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at scott.wemessage.server.c.a.<init>(SourceFile:120)
	at scott.wemessage.server.a.<init>(SourceFile:79)
	at scott.wemessage.server.ServerLauncher.main(SourceFile:8)
 
 
The email and password provided in config.json are invalid!
 
Please enter a new email and password for devices to connect with!
Your email must be the same as the one you are using iMessage with.

**Comment by jobrayan** [comment]
Same issue, looks like a bug. 

Build 1.2 (downloaded at: April 3, 2021 at 3:23 PM)
According to reference from [official tutorial from weMessage](https://youtu.be/XfWnDTwPLNk?t=246)
**Expected result:** After user execute file `run.command.sh` in folder `WeServer` - User navigation switched to the Terminal window. And in the terminal following text should appear: 

`The email and password provided in config.json are invalid!`
`Please enter a new email and password for devices to connect with!`
`Your email must be the same as the one you are using iMessage with.`

After which user  - have ability/can enter - their email in the _terminal line_

**Actual result:** After user executed file `run.command.sh` 
_It shows:_

`The email and password provided in config.json are invalid!`
`Please enter a new email and password for devices to connect with!`
`Your email must be the same as the one you are using iMessage with.`

_ - comment - After which prompt error message:_ 
`[!!! ERROR !!!] [weServer Database Service] An error occurred while connecting to the Messages Chat database. Shutting down!
 
[04-04-2021 00:10:50] java.sql.SQLException: The database has been closed
	at org.sqlite.core.NativeDB.throwex(NativeDB.java:471)
	at org.sqlite.core.NativeDB.errmsg_utf8(Native Method)
	at org.sqlite.core.NativeDB.errmsg(NativeDB.java:137)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB._open_utf8(Native Method)
	at org.sqlite.core.NativeDB._open(NativeDB.java:71)
	at org.sqlite.core.DB.open(DB.java:174)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:25)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at scott.wemessage.server.c.a.<init>(SourceFile:120)
	at scott.wemessage.server.a.<init>(SourceFile:79)
	at scott.wemessage.server.ServerLauncher.main(SourceFile:8)

 
 
[04-04-2021 00:10:52] The email and password provided in config.json are invalid!
 
[04-04-2021 00:10:52] Please enter a new email and password for devices to connect with!
[04-04-2021 00:10:52] Your email must be the same as the one you are using iMessage with.`


_Comment: And user can't enter their email_

**Device details:** OS: MacOs Big Sur Version 11.2.3, Firefox 87.0

**Comment by ceciljchen** [comment]
Experiencing the same issue.
OS X 10.15.7
Java V8 Update 281 (build 1.8.0_281-b09)
WeServer 1.2

A config.json file is created upon first run that contains a default e-mail and password that wasn't input by user.

**Comment by ceciljchen** [comment]
#23 Comment here worked for me. [Full Disk Access](https://github.com/BurtonAlgorithms/weMessage/issues/23#issuecomment-601500854)

**Comment by mlaskin** [comment]
> Experiencing the same issue.
> OS X 10.15.7
> Java V8 Update 281 (build 1.8.0_281-b09)
> WeServer 1.2
> 
> A config.json file is created upon first run that contains a default e-mail and password that wasn't input by user.

Same here
OS X 10.15.7
Java V7 1.7.0_25-b15
WeServer 1.2

Pretty stuck on this - any advice?

Thanks!

**Comment by mlaskin** [comment]
https://github.com/BurtonAlgorithms/weMessage/issues/27#issuecomment-572307135 
explains that you need to give Full Disk Access to java
Once that's done it worked.

**Comment by jobrayan** [comment]
Thank you, will try. And let you know.
